export enum CardName {
  // ── # / A ─────────────────────────────────────────────────────────────────
  NOT_COOL_BRO = 'Not Cool Bro',
  PRINTED_WALLS = '3D Printed Walls',
  RANDOM_TEN_DOLLAR = 'A random ten dollar bill',
  A_PLUS_STUDENT = 'A+ Student',
  ABANDONED_LOCKER = 'Abandoned Notebook',
  ALLERGIES = 'Allergies',
  AMBUSHED = 'Ambushed',
  ANNOUNCEMENT = 'Announcement',
  AREA_SABOTAGE = 'Area Sabotage',
  ATM = 'ATM',
  ATTENDANCE_SHEET = 'Attendance Sheet',

  // ── B ─────────────────────────────────────────────────────────────────────
  BACKPACK_SEARCH = 'Backpack Search',
  BACKPACK_SUPPLIES = 'Backpack with Supplies',
  BAIT_LAUNCHER = 'Bait Launcher',
  BANNED_BOOK = 'Banned Book',
  BATHROOM_TRAP = 'Bathroom Trap',
  BLIND_JUMP = 'Blind Jump',
  BOOBY_TRAPS = 'Booby Traps',
  BOOK_BARRIERS = 'Book Barriers',
  BOOK_RETURN_SLOT = 'Book Return Slot',
  BOOKMARK = 'Bookmark',
  BRASS_KNUCKLES = 'Brass Knuckles',
  BROOM_HANDLE = 'Broom Handle',
  BROWN_BAG_NEGOTIATION = 'Brown Bag Negotiation',

  // ── C ─────────────────────────────────────────────────────────────────────
  CHANGE_IN_CHARACTER = 'Change in Character',
  CHEAT_SHEET = 'Cheat Sheet',
  CHECK_ITS_POCKETS = "Check it's Pockets",
  CHICKEN_DINNER = 'Chicken Dinner',
  CLAIRVOYANCE = 'Clairvoyance',
  CLASS_CLOWN = 'Class Clown',
  CLASS_CURVE = 'Class Curve',
  CLASSIC_FICTION = 'Classic Fiction',
  CONFIDENT_FIRST_STEP = 'Confident First Step',
  COPIED_NOTES = 'Copied Notes',
  CPR_CLASS = 'CPR Class',
  CRAM_SESSION = 'Cram Session',
  CROWDED_HALLS = 'Crowded Halls',
  CRUSTY_BAND_AID = 'Crusty Band-Aid',

  // ── D ─────────────────────────────────────────────────────────────────────
  DAREDEVIL = 'Daredevil',
  DARK_RITUAL = 'Open Locker',
  DARK_ROOM_DEVELOPMENTS = 'Dark Room Developments',
  DEATH_SCENT = 'Death Scent',
  DEMERIT_SLIP = 'Demerit Slip',
  DETENTION_SLIP = 'Detention Slip',
  DIRTY_HALL_MONITOR = 'Dirty Hall Monitor',
  DIRTY_WORK = 'Dirty Work',
  DISGUSTING_MESS = 'Disgusting Mess',
  DISTRACTION = 'Distraction',
  DROPPED_CASH = 'Dropped Cash',
  DROPPING_A_COURSE = 'Dropping a Course',
  DUMPSTER_DIVING = 'Dumpster Diving',

  // ── E ─────────────────────────────────────────────────────────────────────
  EMBARRASSMENT = 'Embarassment',
  EMERGENCY_RETREAT = 'Emergency Retreat',
  ENGINEERING_CLUB = 'Engineering Club',
  ENGINEERING_EXAM_KEY = 'Engineering Exam Key',
  EXPERIMENT = 'Experiment',
  EXTRA_MOVEMENT = 'Extra Movement',

  // ── F ─────────────────────────────────────────────────────────────────────
  VISITING_FACULTY_ID = 'Visiting Faculty ID',
  FIRST_AID_KIT = 'First Aid Kit',
  FOOD_FIGHT = 'Food Fight',
  FREE_TRAP_PIECES = 'Free Trap Pieces',

  // ── G ─────────────────────────────────────────────────────────────────────
  GOOD_SCIENCE = 'Good Science',
  GRAFFITI = 'Graffiti',
  GRAVE_ROBBER = 'Grave Robber',
  GYM_CLASS_HERO = 'Gym Class Hero',
  ATHLETIC_FOOTWEAR = 'Athletic Footwear',
  GYMNASTICS_TRAINING = 'Gymnastics Training',

  // ── H ─────────────────────────────────────────────────────────────────────
  HALLWAY_HUSTLER = 'Hallway Hustler',
  HALO_EFFECT = 'Halo Effect',
  HEARTY_LUNCH = 'Hearty Lunch',
  HIDDEN_REPORT_CARD = 'Hidden Report Card',
  HIRED_MUSCLE = 'Hired Muscle',
  HOLE_IN_THE_CEILING = 'Hole in the Ceiling',
  HOMERUN_BAT = 'Homerun Bat',
  HONOR_ROLL = 'Honor Roll',
  HYPNOTISM = 'Hypnotism',

  // ── I ─────────────────────────────────────────────────────────────────────
  IDENTITY_CRISIS = 'Identity Crisis',
  IN_MEMORY_OF = 'In Memory Of...',
  INFLUENCER = 'Influencer',
  IRON_WELDING = 'Iron Welding',

  // ── L ─────────────────────────────────────────────────────────────────────
  LAB_ACCIDENT = 'Lab Accident',
  LAST_MEAL = 'Last Meal',
  LATE_PAPER = 'Late Paper',
  LEFTOVER_LUNCH_TRAY = 'Leftover Lunch Tray',
  WORN_LIBRARY_CARD = 'Worn Library Card',
  LONG_JUMP = 'Long Jump',
  LOUDSPEAKER_ANNOUNCEMENT = 'Loudspeaker Announcement',
  LUNCH_FROM_HOME = 'Lunch from Home',
  LUNCH_MONEY = 'Lunch Money',
  LUNCH_TRAY = 'Lunch Tray',

  // ── M ─────────────────────────────────────────────────────────────────────
  MAD_DASH = 'Mad Dash',
  MAILROOM_CART = 'Mailroom Cart',
  MENTAL_PREPARATION = 'Mental Preparation',
  MERCY = 'Mercy',
  MISSING_HALLPASS = 'Missing Hallpass',
  MORNING_JOGGING_CLUB = 'Morning Jogging Club',
  MOUTH_GUARD = 'Mouth Guard',
  MR_CLEAN = 'Mr. Clean',
  MYSTERY_MEAT = 'Mystery Meat',

  // ── N ─────────────────────────────────────────────────────────────────────
  NEWSPAPER_INTERVIEW = 'Newspaper Interview',
  NICE_GUYS_FINISH_LAST = 'Nice Guys Finish Last',
  NICE_REMOVAL = 'Nice Removal',
  NOBODY_SAW_THAT = 'Nobody Saw That',
  NURSES_STATION = "Nurse's Station",

  // ── O ─────────────────────────────────────────────────────────────────────
  OLD_SANDWICH = 'Old Sandwich',
  ONE_VS_ONE = 'One vs One',
  OOPS = 'Oops!',

  // ── P ─────────────────────────────────────────────────────────────────────
  PANIC_RUN = 'Panic Run',
  PARAMEDIC_KIT = 'Paramedic Kit',
  PASSED_NOTE = 'Passed Note',
  PASSED_SHOP_CLASS = 'Passed Shop Class',
  PE_SHORTS = 'PE Shorts',
  PERMISSION_SLIP = 'Permission Slip',
  PHYSICAL_EXERCISE = 'Physical Exercise',
  PLAGIARISM = 'Plaigarism',
  POCKET_TRAP = 'Pocket Trap',
  POPULARITY = 'Popularity',
  PRACTICAL_JOKE = 'Practical Joke',
  PRINCIPALS_SECRET = "Principal's Secret",
  PROTECTION_MONEY = 'Protection Money',

  // ── R ─────────────────────────────────────────────────────────────────────
  RECYCLED_BARRICADE = 'Recycled Barricade Materials',
  RECYCLING_CLUB = 'Recycling Club',
  REGRET = 'Regret',
  RUNNING_JUMP = 'Running Jump',

  // ── S ─────────────────────────────────────────────────────────────────────
  SAVED_YOU_A_SEAT = 'Saved you a Seat',
  SCIENCE_KIT = 'Science Kit',
  SECRET_NOTES = 'Secret Notes',
  SECRET_PASSAGE = 'Secret Passage',
  SELL_A_KIDNEY = 'Sell a Kidney',
  SELL_OUT = 'Sell Out',
  SENIOR_PRANK = 'Senior Prank',
  SHOP_TEACHERS_PET = "Shop Teacher's Pet",
  SHUT_THAT_DOOR = 'Shut that Door!',
  SIDE_HUSTLE = 'Side Hustle',
  SINCERE_THANKS = 'Sincere Thanks',
  SKATEBOARD_ACCIDENT = 'Skateboard Accident',
  SKIPPING_LUNCH = 'Skipping Lunch Today',
  SNACK_TRACK = 'Snack Track',
  SOCIAL_BLUR = 'Social Blur',
  SPATIAL_SWAP = 'Spatial Swap',
  SPLIT_UP = 'Split Up',
  SPOILED_MILK = 'Spoiled Milk',
  SPONSORSHIP = 'Sponsorship',
  SPOTTING_FOR_STRANGER = 'Spotting for a Stranger',
  STAYING_AWAKE = 'Staying Awake',
  STEM_CLUB = 'STEM Club',
  STOLEN_WALLET = 'Stolen Wallet',
  STUDENT_DISCOUNT = 'Student Discount',
  STUDENT_OF_THE_MONTH = 'Student of the Month',
  STUDY_GROUP = 'Study Group',

  // ── T ─────────────────────────────────────────────────────────────────────
  TAKING_A_BRIBE = 'Taking a Bribe',
  TAKING_A_NAP = 'Taking a Nap',
  TALENT_SHOW = 'Talent Show',
  TEACHERS_PET = "Teacher's Pet",
  TERMITE_DAMAGE = 'Termite Damage',
  TERROR_SPRINT = 'Terror Sprint',
  THANK_YOU_NOTE = 'Thank You Note',
  THERAPY_GROUP = 'Therapy Group',
  THEY_JUST_KEEP_COMING = 'They just keep coming!',
  TIME_OUT = 'Time Out',
  TOE_SOCKS = 'Toe Socks',
  TOOLBELT = 'Toolbelt',
  TRANSFUSION = 'Transfusion',
  TRAP_FLEX = 'Trap Flex',
  TRIPLE_JUMP = 'Triple Jump',

  // ── U ─────────────────────────────────────────────────────────────────────
  UNDER_THE_TABLE = 'Under the Table',
  UNDERGROUND_PASSAGEWAY = 'Underground Passageway',

  // ── V ─────────────────────────────────────────────────────────────────────
  VALEDICTORIANS_NOTEBOOK = "Valedictorian's Notebook",
  VENDING_MACHINE_SCAPES = 'Vending Machine Scraps',

  // ── W ─────────────────────────────────────────────────────────────────────
  LUNCHLADY_HELPER = "Lunchlady's Helper",
  WALL_IT_OFF = 'Wall it Off!',
  WAS_THAT_LOAD_BEARING = 'Was that Load Bearing?',
  WATER_COOLER = 'Water Cooler',
  WELL_WORN_BOOK = 'Well-worn Book',

  // ── Z ─────────────────────────────────────────────────────────────────────
  ZOMBIE_FLUSH = 'Zombie Flush',

  // ── LEGACY (kept for backward compat; not in active deck) ─────────────────
  ADVANCED_TRAINING = 'Advanced Training',
  ALERTNESS = 'Alertness',
  BAIT_DEPLOYER = 'Bait Deployer',
  BAIT_FANATIC = 'Bait Fanatic',
  BAIT_POUCH = 'Bait Pouch',
  BAIT_REMOVAL = 'Bait Removal',
  BAIT_SWAP = 'Bait Swap',
  BAIT_TRAINING = 'Bait Training',
  BANK_WITHDRAWAL = 'Bank Withdrawal',
  BARRICADE_RUNNER = 'Barricade Runner',
  BARRICADE_SUPPLIES = 'Barricade Supplies',
  BARRICADE_THEFT = 'Barricade Theft',
  BASIC_TRAINING = 'Basic Training',
  CALL_TO_ACTION = 'Call to Action',
  CHALLENGE = 'Challenge',
  CHEAP_BAIT = 'Cheap Bait',
  CHEAPER_BAIT = 'Cheaper Bait',
  COMBAT_MEDIC = 'Combat Medic',
  COMMUNITY_FUND = 'Community Fund',
  COMMUNITY_SUPPORT = 'Community Support',
  CRITICAL_RATIONS = 'Critical Rations',
  CROWDED_STREETS = 'Crowded Streets',
  DARK_SECRETS = 'Dark Secrets',
  DEMOLITION = 'Demolition',
  DESPAIR_TRAP = 'Despair Trap',
  EMERGENCY_DRAW = 'Emergency Draw',
  EMERGENCY_RATIONS = 'Emergency Rations',
  EXPERT_DEFENSE = 'Expert Defense',
  EXTRA_RATIONS = 'Extra Rations',
  FINAL_GAMBIT = 'Final Gambit',
  FINAL_PREPARATION = 'Final Preparation',
  FIRST_AID = 'First Aid',
  GROUP_TRAINING = 'Group Training',
  HEROS_APPRENTICE = "Hero's Apprentice",
  HEROS_CACHE = "Hero's Cache",
  HEROS_CHARGE = "Hero's Charge",
  HEROS_LOOT = "Hero's Loot",
  HEROS_TRAINING = "Hero's Training",
  HEROIC_DONATION = 'Heroic Donation',
  HEROIC_KILL = 'Heroic Kill',
  HEROIC_RESOLVE = 'Heroic Resolve',
  HIDDEN_TREASURE = 'Hidden Treasure',
  JUNK_COLLECTOR = 'Junk Collector',
  LAST_STAND = 'Last Stand',
  MASTER_BUILDER = 'Master Builder',
  MASTER_PLAN = 'Master Plan',
  MEDAL_CEREMONY = 'Medal Ceremony',
  MEDIC_KIT = 'Medic Kit',
  MEDICS_KIT = "Medic's Kit",
  MOBILITY_TRAINING = 'Mobility Training',
  NIGHT_WATCH = 'Night Watch',
  OLD_TRAP = 'Old Trap',
  PAIN_ENJOYMENT = 'Pain Enjoyment',
  PARKOUR_EXPERT = 'Parkour Expert',
  PAWNED_GOODS = 'Pawned Goods',
  PAWNED_HONORS = 'Pawned Honors',
  PLOY = 'Ploy',
  PREPARATION = 'Preparation',
  QUICK_BARRICADE = 'Quick Barricade',
  QUICK_FINGERS = 'Quick Fingers',
  QUICK_HANDS = 'Quick Hands',
  QUICK_WEALTH = 'Quick Wealth',
  QUIET_STEPS = 'Quiet Steps',
  RAPID_BARRICADES = 'Rapid Barricades',
  REGRETFUL_DESTRUCTION = 'Regretful Destruction',
  REINFORCEMENT_ORDER = 'Reinforcement Order',
  REINFORCEMENTS = 'Reinforcements',
  REPENTANCE = 'Repentance',
  ROTTEN_BAIT = 'Rotten Bait',
  ROYAL_DECREE = 'Royal Decree',
  RUINED_TROPHY = 'Ruined Trophy',
  SABOTAGE_ORDER = 'Sabotage Order',
  SACRIFICE = 'Sacrifice',
  SCHEME = 'Scheme',
  SCOUTING_REPORT = 'Scouting Report',
  SCROUNGER = 'Scrounger',
  SECRET_PLANS = 'Secret Plans',
  SINFUL_ACT = 'Sinful Act',
  SLOW_WEALTH = 'Slow Wealth',
  SMALL_LOOT = 'Small Loot',
  SOUL_CONTRACT = 'Soul Contract',
  SPARE_PARTS = 'Spare Parts',
  STOLEN_GOODS = 'Stolen Goods',
  STOLEN_HONORS = 'Stolen Honors',
  STRATEGIC_DRAW = 'Strategic Draw',
  STRATEGIC_MOVEMENT = 'Strategic Movement',
  STRUCTURAL_SABOTAGE = 'Structural Sabotage',
  SUICIDE_BURN = 'Suicide Burn',
  SUPPLY_DROP = 'Supply Drop',
  SURVIVAL_INSTINCT = 'Survival Instinct',
  SURVIVAL_KILL = 'Survival Kill',
  SURVIVORS_CACHE = "Survivor's Cache",
  SURVIVORS_TRADE = "Survivor's Trade",
  SWIFT_MOVEMENT = 'Swift Movement',
  TACTICAL_DRAW = 'Tactical Draw',
  TACTICAL_MOVEMENT = 'Tactical Movement',
  THREAT_MANAGEMENT = 'Threat Management',
  TOLL_REDUCTION = 'Toll Reduction',
  TOTAL_REGRET = 'Total Regret',
  TRAINING_REGIMEN = 'Training Regimen',
  TRAP_COMPONENTS = 'Trap Components',
  TRAP_MASTER = 'Trap Master',
  TRAP_RELOCATION = 'Trap Relocation',
  TRAP_REMOVAL = 'Trap Removal',
  TRAP_SABOTAGE = 'Trap Sabotage',
  TRAP_STARTER = 'Trap Starter',
  TRAP_STOCKPILE = 'Trap Stockpile',
  TRAP_SUPPLIES = 'Trap Supplies',
  TRICK = 'Trick',
  UNCOVERED_LOCKER = 'Uncovered Locker Item',
  VICTORY_PARADE = 'Victory Parade',
  VILLAIN_GUILD = 'Villain Guild',
  VILLAINS_CACHE = "Villain's Cache",
  VILLAINS_MINION = "Villain's Minion",
  VILLAINS_TRAINING = "Villain's Training",
  VILLAINS_TRAP = "Villain's Trap",
  VILLAINOUS_AMBITION = 'Villainous Ambition',
  VILLAINOUS_THEFT = 'Villainous Theft',
  WARNING_SHOT = 'Warning Shot',
  ZOMBIE_BEACON = 'Zombie Beacon',
  ZOMBIE_BOUNTY = 'Zombie Bounty',
  ZOMBIE_HERDER = 'Zombie Herder',
  ZOMBIE_KILL = 'Zombie Kill',

  // ── Hero passives (internal CardRegistry keys) ────────────────────────────
  HERO_SCHADENFREUDE_PASSIVE = 'Schadenfreude Passive',
  HERO_BARRY_CADE_PASSIVE = 'Barry Cade Passive',
  HERO_VON_TRAP_PASSIVE = 'Von Trap Passive',
  HERO_BLOODTHIRSTER_PASSIVE = 'Bloodthirster Passive',
  HERO_SPOTTER_PASSIVE = 'Spotter Passive',
  HERO_BUNGLER_PASSIVE = 'Bungler Passive',
  HERO_ARCHY_TECT_PASSIVE = 'Archy Tect Passive',
  HERO_LOAN_WOLF_PASSIVE = 'Loan Wolf Passive',
  HERO_GYM_COACH_PASSIVE = 'Gym Coach Passive',

  // ── Locker item passives (internal CardRegistry keys) ───────────────────────────
  LOCKER_SHOES_PASSIVE = 'Shoes Passive',
  LOCKER_LEATHER_JACKET_PASSIVE = 'Leather Jacket Passive',
  LOCKER_ROLLER_BACKPACK_PASSIVE = 'Roller Backpack Passive',
  LOCKER_DOG_TAGS_PASSIVE = 'Dog Tags Passive',
  LOCKER_CHILDS_TOOL_SET_PASSIVE = "Child's Tool Set Passive",
  LOCKER_DIRTY_GYM_SOCKS_PASSIVE = 'Dirty Gym Socks Passive',
  LOCKER_SCOUT_TRAINING_PASSIVE = 'Scout Training Passive',
  LOCKER_QUALITY_OVER_QUANTITY_PASSIVE = 'Quality over Quantity Passive',
  LOCKER_SHARPENED_STICK_PASSIVE = 'Sharpened Stick Passive',
  LOCKER_GAS_LEAK_PASSIVE = 'Gas Leak Passive',
}
