export enum LockerId {
  OUJI_BOARD = 'ouji_board',
  SHOES = 'shoes',
  LEATHER_JACKET = 'leather_jacket',
  ROLLER_BACKPACK = 'roller_backpack',
  LONG_SLEEVES = 'long_sleeves',
  PYRAMID_SCHEME = 'pyramid_scheme',
  FRESH_WOUND_DRESSING = 'fresh_wound_dressing',
  DOG_TAGS = 'dog_tags',
  WALL_IN_A_BOX = 'wall_in_a_box',
  CHARITY_FUND = 'charity_fund',
  CHILDS_TOOL_SET = 'childs_tool_set',
  GRAPPLING_HOOK = 'grappling_hook',
  VITAMINS = 'vitamins',
  PERMANENT_RECORD = 'permanent_record',
  FREE_HUGS_T_SHIRT = 'free_hugs_t_shirt',
  DIRTY_GYM_SOCKS = 'dirty_gym_socks',
  PART_TIME_JOB = 'part_time_job',
  SCOUT_TRAINING = 'scout_training',
  NICE_FOR_SALE = 'nice_for_sale',
  COOL_FOR_SALE = 'cool_for_sale',
  QUALITY_OVER_QUANTITY = 'quality_over_quantity',
  SHARPENED_STICK = 'sharpened_stick',
  GAS_LEAK = 'gas_leak',
}
